// <auto-generated />
using System;
using GovAI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GovAI.Persistence.Migrations
{
    [DbContext(typeof(GovAiDbContext))]
    partial class GovAiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("govai")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GovAI.Domain.Assessments.AssessmentDimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Contribution")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("contribution");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer")
                        .HasColumnName("dimension");

                    b.Property<Guid>("EligibilityAssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("eligibility_assessment_id");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rationale");

                    b.Property<decimal>("Value")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("value");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_assessment_dimensions");

                    b.HasIndex("EligibilityAssessmentId")
                        .HasDatabaseName("ix_assessment_dimensions_eligibility_assessment_id");

                    b.ToTable("assessment_dimensions", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Assessments.EligibilityAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BlockingFailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("blocking_failure_count");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("CompanyProfileVersion")
                        .HasColumnType("integer")
                        .HasColumnName("company_profile_version");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DataGapCount")
                        .HasColumnType("integer")
                        .HasColumnName("data_gap_count");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("ExecutiveSummary")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("executive_summary");

                    b.Property<decimal>("FinalScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("final_score");

                    b.Property<bool>("HasBlockingFailure")
                        .HasColumnType("boolean")
                        .HasColumnName("has_blocking_failure");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_latest");

                    b.Property<int>("MissingConditionCount")
                        .HasColumnType("integer")
                        .HasColumnName("missing_condition_count");

                    b.Property<int>("MissingMandatoryDocumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("missing_mandatory_document_count");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<DateTimeOffset?>("SummaryGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("summary_generated_at");

                    b.Property<string>("SummaryModel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("summary_model");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_eligibility_assessments");

                    b.HasIndex("EvaluatedAt")
                        .HasDatabaseName("ix_eligibility_assessments_evaluated_at");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("ix_eligibility_assessments_opportunity_id");

                    b.HasIndex("CompanyId", "IsLatest", "FinalScore")
                        .HasDatabaseName("ix_eligibility_assessments_company_id_is_latest_final_score");

                    b.HasIndex("CompanyId", "OpportunityId", "IsLatest")
                        .HasDatabaseName("ix_eligibility_assessments_company_id_opportunity_id_is_latest");

                    b.ToTable("eligibility_assessments", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Assessments.ScenarioImpact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaselineScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("baseline_score");

                    b.Property<int>("BaselineVerdict")
                        .HasColumnType("integer")
                        .HasColumnName("baseline_verdict");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("OpportunityTitle")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("opportunity_title");

                    b.Property<Guid>("ScenarioSimulationId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_simulation_id");

                    b.Property<decimal>("SimulatedScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("simulated_score");

                    b.Property<int>("SimulatedVerdict")
                        .HasColumnType("integer")
                        .HasColumnName("simulated_verdict");

                    b.HasKey("Id")
                        .HasName("pk_scenario_impacts");

                    b.HasIndex("ScenarioSimulationId")
                        .HasDatabaseName("ix_scenario_impacts_scenario_simulation_id");

                    b.ToTable("scenario_impacts", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Assessments.ScenarioSimulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaselineAverageScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("baseline_average_score");

                    b.Property<int>("BaselineEligibleCount")
                        .HasColumnType("integer")
                        .HasColumnName("baseline_eligible_count");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("SimulatedAverageScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("simulated_average_score");

                    b.Property<int>("SimulatedEligibleCount")
                        .HasColumnType("integer")
                        .HasColumnName("simulated_eligible_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_scenario_simulations");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_scenario_simulations_company_id");

                    b.ToTable("scenario_simulations", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("UserEmail")
                        .HasDatabaseName("ix_audit_log_user_email");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id");

                    b.ToTable("audit_log", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("ExportFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("export_flag");

                    b.Property<DateOnly?>("FoundedOn")
                        .HasColumnType("date")
                        .HasColumnName("founded_on");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("legal_name");

                    b.Property<int>("LegalType")
                        .HasColumnType("integer")
                        .HasColumnName("legal_type");

                    b.Property<int>("PreviousSuccessfulApplications")
                        .HasColumnType("integer")
                        .HasColumnName("previous_successful_applications");

                    b.Property<int>("ProfileVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("profile_version");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_number");

                    b.Property<bool>("TechnologyFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("technology_flag");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_companies_tenant_id");

                    b.HasIndex("TenantId", "TaxNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_tenant_id_tax_number");

                    b.ToTable("companies", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Companies.CompanyCertificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("DocumentUri")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("document_uri");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_company_certificates");

                    b.HasIndex("CompanyId", "Code")
                        .HasDatabaseName("ix_company_certificates_company_id_code");

                    b.ToTable("company_certificates", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Companies.CompanyInvestment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<decimal>("PlannedBudget")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("planned_budget");

                    b.Property<DateOnly?>("PlannedEnd")
                        .HasColumnType("date")
                        .HasColumnName("planned_end");

                    b.Property<DateOnly?>("PlannedStart")
                        .HasColumnType("date")
                        .HasColumnName("planned_start");

                    b.Property<int>("RelatedCategory")
                        .HasColumnType("integer")
                        .HasColumnName("related_category");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_company_investments");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_investments_company_id");

                    b.ToTable("company_investments", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Companies.CompanyLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<bool>("IsHeadquarters")
                        .HasColumnType("boolean")
                        .HasColumnName("is_headquarters");

                    b.Property<bool>("IsInTechnopark")
                        .HasColumnType("boolean")
                        .HasColumnName("is_in_technopark");

                    b.Property<string>("Nuts2Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nuts2code");

                    b.HasKey("Id")
                        .HasName("pk_company_locations");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_locations_company_id");

                    b.HasIndex("Nuts2Code")
                        .HasDatabaseName("ix_company_locations_nuts2code");

                    b.ToTable("company_locations", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Companies.CompanyNaceCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.HasKey("Id")
                        .HasName("pk_company_nace_codes");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_company_nace_codes_company_id_code");

                    b.ToTable("company_nace_codes", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_subject_id");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("ScopedCompanyIdsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("scoped_company_ids_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Identity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxCompanies")
                        .HasColumnType("integer")
                        .HasColumnName("max_companies");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("plan");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("deduplication_key");

                    b.Property<int>("DeliveryAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_attempt_count");

                    b.Property<string>("DeliveryError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("delivery_error");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_deduplication_key");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_notifications_sent_at");

                    b.HasIndex("TenantId", "CompanyId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_tenant_id_company_id_created_at");

                    b.ToTable("notifications", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Opportunities.DocumentRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mandatory");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("issuing_authority");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.HasKey("Id")
                        .HasName("pk_opportunity_documents");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("ix_opportunity_documents_opportunity_id");

                    b.ToTable("opportunity_documents", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Opportunities.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsReviewedByConsultant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reviewed_by_consultant");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("publisher");

                    b.Property<decimal>("RuleExtractionConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("rule_extraction_confidence");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("summary");

                    b.Property<int>("SupportCategory")
                        .HasColumnType("integer")
                        .HasColumnName("support_category");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_opportunities");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("ix_opportunities_deadline");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_opportunities_published_at");

                    b.HasIndex("SourceDocumentId")
                        .IsUnique()
                        .HasDatabaseName("ix_opportunities_source_document_id")
                        .HasFilter("source_document_id IS NOT NULL");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_opportunities_source_id");

                    b.HasIndex("SupportCategory")
                        .HasDatabaseName("ix_opportunities_support_category");

                    b.ToTable("opportunities", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Opportunities.OpportunityRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer")
                        .HasColumnName("dimension");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("field");

                    b.Property<string>("HumanReadable")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("human_readable");

                    b.Property<bool>("IsManuallyOverridden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manually_overridden");

                    b.Property<int>("Operator")
                        .HasColumnType("integer")
                        .HasColumnName("operator");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("SourceExcerpt")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("source_excerpt");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_opportunity_rules");

                    b.HasIndex("Dimension")
                        .HasDatabaseName("ix_opportunity_rules_dimension");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("ix_opportunity_rules_opportunity_id");

                    b.ToTable("opportunity_rules", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Sources.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("base_url");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failure_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cron_expression");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("LastRunMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_run_message");

                    b.Property<int>("LastRunStatus")
                        .HasColumnType("integer")
                        .HasColumnName("last_run_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_sources_is_enabled");

                    b.ToTable("sources", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Sources.SourceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("media_type");

                    b.Property<string>("NormalizedText")
                        .HasColumnType("text")
                        .HasColumnName("normalized_text");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("processing_error");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_source_documents");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_source_documents_content_hash");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_source_documents_status");

                    b.HasIndex("SourceId", "Url")
                        .IsUnique()
                        .HasDatabaseName("ix_source_documents_source_id_url");

                    b.ToTable("source_documents", "govai");
                });

            modelBuilder.Entity("GovAI.Domain.Assessments.AssessmentDimension", b =>
                {
                    b.HasOne("GovAI.Domain.Assessments.EligibilityAssessment", null)
                        .WithMany("Dimensions")
                        .HasForeignKey("EligibilityAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_dimensions_assessments_eligibility_assessment_id");
                });

            modelBuilder.Entity("GovAI.Domain.Assessments.EligibilityAssessment", b =>
                {
                    b.HasOne("GovAI.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eligibility_assessments_companies_company_id");

                    b.HasOne("GovAI.Domain.Opportunities.Opportunity", null)
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eligibility_assessments_opportunities_opportunity_id");
                });

            modelBuilder.Entity("GovAI.Domain.Assessments.ScenarioImpact", b =>
                {
                    b.HasOne("GovAI.Domain.Assessments.ScenarioSimulation", null)
                        .WithMany("Impacts")
                        .HasForeignKey("ScenarioSimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scenario_impacts_scenario_simulations_scenario_simulation_id");
                });

            modelBuilder.Entity("GovAI.Domain.Companies.Company", b =>
                {
                    b.OwnsOne("GovAI.Domain.Companies.Financials", "Financials", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("AnnualRevenue")
                                .HasPrecision(20, 2)
                                .HasColumnType("numeric(20,2)")
                                .HasColumnName("annual_revenue");

                            b1.Property<decimal>("BalanceSize")
                                .HasPrecision(20, 2)
                                .HasColumnType("numeric(20,2)")
                                .HasColumnName("balance_size");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Equity")
                                .HasPrecision(20, 2)
                                .HasColumnType("numeric(20,2)")
                                .HasColumnName("equity");

                            b1.Property<decimal>("ExportRevenue")
                                .HasPrecision(20, 2)
                                .HasColumnType("numeric(20,2)")
                                .HasColumnName("export_revenue");

                            b1.Property<int?>("FiscalYear")
                                .HasColumnType("integer")
                                .HasColumnName("fiscal_year");

                            b1.HasKey("CompanyId");

                            b1.ToTable("companies", "govai");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId")
                                .HasConstraintName("fk_companies_companies_id");
                        });

                    b.OwnsOne("GovAI.Domain.Companies.Workforce", "Workforce", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("DisabledEmployeeCount")
                                .HasColumnType("integer")
                                .HasColumnName("disabled_employee_count");

                            b1.Property<int>("EmployeeCount")
                                .HasColumnType("integer")
                                .HasColumnName("employee_count");

                            b1.Property<int>("RAndDEmployeeCount")
                                .HasColumnType("integer")
                                .HasColumnName("rnd_employee_count");

                            b1.Property<int>("WomenEmployeeCount")
                                .HasColumnType("integer")
                                .HasColumnName("women_employee_count");

                            b1.Property<int>("YoungEmployeeCount")
                                .HasColumnType("integer")
                                .HasColumnName("young_employee_count");

                            b1.HasKey("CompanyId");

                            b1.ToTable("companies", "govai");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId")
                                .HasConstraintName("fk_companies_companies_id");
                        });

                    b.Navigation("Financials")
                        .IsRequired();

                    b.Navigation("Workforce")
                        .IsRequired();
                });

            modelBuilder.Entity("GovAI.Domain.Companies.CompanyCertificate", b =>
                {
                    b.HasOne("GovAI.Domain.Companies.Company", null)
                        .WithMany("Certificates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_certificates_companies_company_id");
                });

            modelBuilder.Entity("GovAI.Domain.Companies.CompanyInvestment", b =>
                {
                    b.HasOne("GovAI.Domain.Companies.Company", null)
                        .WithMany("ActiveInvestments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_investments_companies_company_id");
                });

            modelBuilder.Entity("GovAI.Domain.Companies.CompanyLocation", b =>
                {
                    b.HasOne("GovAI.Domain.Companies.Company", null)
                        .WithMany("Locations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_locations_companies_company_id");
                });

            modelBuilder.Entity("GovAI.Domain.Companies.CompanyNaceCode", b =>
                {
                    b.HasOne("GovAI.Domain.Companies.Company", null)
                        .WithMany("NaceCodes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_nace_codes_companies_company_id");
                });

            modelBuilder.Entity("GovAI.Domain.Identity.AppUser", b =>
                {
                    b.HasOne("GovAI.Domain.Identity.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");
                });

            modelBuilder.Entity("GovAI.Domain.Opportunities.DocumentRequirement", b =>
                {
                    b.HasOne("GovAI.Domain.Opportunities.Opportunity", null)
                        .WithMany("DocumentChecklist")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opportunity_documents_opportunities_opportunity_id");
                });

            modelBuilder.Entity("GovAI.Domain.Opportunities.Opportunity", b =>
                {
                    b.HasOne("GovAI.Domain.Sources.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_opportunities_sources_source_id");

                    b.OwnsOne("GovAI.Domain.Opportunities.BudgetRange", "Budget", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("budget_currency");

                            b1.Property<decimal?>("MaxAmount")
                                .HasPrecision(20, 2)
                                .HasColumnType("numeric(20,2)")
                                .HasColumnName("budget_max");

                            b1.Property<decimal?>("MinAmount")
                                .HasPrecision(20, 2)
                                .HasColumnType("numeric(20,2)")
                                .HasColumnName("budget_min");

                            b1.Property<decimal?>("SupportRate")
                                .HasPrecision(5, 4)
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("support_rate");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("opportunities", "govai");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId")
                                .HasConstraintName("fk_opportunities_opportunities_id");
                        });

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("GovAI.Domain.Opportunities.OpportunityRule", b =>
                {
                    b.HasOne("GovAI.Domain.Opportunities.Opportunity", null)
                        .WithMany("Rules")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opportunity_rules_opportunities_opportunity_id");
                });

            modelBuilder.Entity("GovAI.Domain.Sources.SourceDocument", b =>
                {
                    b.HasOne("GovAI.Domain.Sources.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_documents_sources_source_id");
                });

            modelBuilder.Entity("GovAI.Domain.Assessments.EligibilityAssessment", b =>
                {
                    b.Navigation("Dimensions");
                });

            modelBuilder.Entity("GovAI.Domain.Assessments.ScenarioSimulation", b =>
                {
                    b.Navigation("Impacts");
                });

            modelBuilder.Entity("GovAI.Domain.Companies.Company", b =>
                {
                    b.Navigation("ActiveInvestments");

                    b.Navigation("Certificates");

                    b.Navigation("Locations");

                    b.Navigation("NaceCodes");
                });

            modelBuilder.Entity("GovAI.Domain.Opportunities.Opportunity", b =>
                {
                    b.Navigation("DocumentChecklist");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
